# Generated by Django 3.1.4 on 2020-12-28 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_table', models.FileField(upload_to='', verbose_name='Стартовый шаблон')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала проекта')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания')),
                ('last_it', models.IntegerField(default=0, verbose_name='Последняя итерация')),
                ('status', models.IntegerField(choices=[(0, 'Готов к созданию отчета!'), (1, 'Собираю информацию!'), (2, 'Необходимо разметить материал!'), (3, 'Скачать таблицу!')], default=0, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='Запрос')),
                ('yandex_header', models.ImageField(blank=True, null=True, upload_to='')),
                ('google_header', models.ImageField(blank=True, null=True, upload_to='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.person', verbose_name='Персона')),
            ],
        ),
        migrations.CreateModel(
            name='Url_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.IntegerField(choices=[(0, 'позитив'), (1, 'негатив'), (-1, 'не размечено')], default=-1, verbose_name='Тональность')),
                ('href', models.CharField(max_length=400, unique=True, verbose_name='Ссылка')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.person', verbose_name='Персона')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=400, verbose_name='Ссылка')),
                ('search_system', models.CharField(max_length=200, verbose_name='Поисковая система')),
                ('image', models.ImageField(default='1_yandex_header.png', upload_to='', verbose_name='Картинка')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('page_number', models.IntegerField(default=0, verbose_name='Номер страницы')),
                ('page_position', models.IntegerField(default=0, verbose_name='Номер ссылки в странице')),
                ('last_it', models.IntegerField(default=0, verbose_name='Последняя итерация')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.query', verbose_name='Запрос')),
                ('url_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.url_data', verbose_name='Ссылка в базе')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=400, verbose_name='Таблица отчета')),
                ('letter', models.CharField(max_length=400, verbose_name='Сопроводительное письмо')),
                ('table_name', models.CharField(max_length=200, verbose_name='Имя таблицы')),
                ('letter_name', models.CharField(max_length=200, verbose_name='Название письма')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('last_it', models.IntegerField(default=0, verbose_name='Последняя итерация')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.person', verbose_name='Персона')),
            ],
        ),
        migrations.CreateModel(
            name='Exception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(max_length=200, verbose_name='Тональность')),
                ('href', models.CharField(max_length=400, verbose_name='Ссылка')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.person', verbose_name='Персона')),
            ],
        ),
    ]
